# services:
#   api:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       db:
#         condition: service_healthy
#     environment:
#       - DATABASE_URL=postgresql://user:password@db:5432/trustdb
#       - PORT=3000
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
    
#   db:
#     image: postgres:14
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=trustdb
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U user -d trustdb"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:AIKON_2@167.172.66.102:5432/aikon
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules